// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmUui2yxf34MxNrKepjvJn5hrqlzHbQqw',
    appId: '1:248929538524:web:5d1ef701db946b0fbb7f19',
    messagingSenderId: '248929538524',
    projectId: 'e-money-ef278',
    authDomain: 'e-money-ef278.firebaseapp.com',
    storageBucket: 'e-money-ef278.firebasestorage.app',
    measurementId: 'G-CZ90M3M2QG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKA7Mzjr2YQdcczFEi_kMo9mfi5AVpl7I',
    appId: '1:248929538524:android:6e5715021f3c4967bb7f19',
    messagingSenderId: '248929538524',
    projectId: 'e-money-ef278',
    storageBucket: 'e-money-ef278.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmUui2yxf34MxNrKepjvJn5hrqlzHbQqw',
    appId: '1:248929538524:web:9e4815a0098fae83bb7f19',
    messagingSenderId: '248929538524',
    projectId: 'e-money-ef278',
    authDomain: 'e-money-ef278.firebaseapp.com',
    storageBucket: 'e-money-ef278.firebasestorage.app',
    measurementId: 'G-FY1Z8G2P7K',
  );
}
